### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by hyochan** [dooboolab/dooboo-ui-native#162]
![dooboo](https://user-images.githubusercontent.com/27461460/73331043-e5c2b000-42a5-11ea-9667-e33d4e02593f.png)

![dooboo-ui](https://user-images.githubusercontent.com/27461460/73331047-ea876400-42a5-11ea-9c9c-1c997eb961be.png)

**Comment by marsinearth** [comment]
![image](https://user-images.githubusercontent.com/6101260/73331611-ad23d600-42a7-11ea-852f-d0e0e1d390d0.png)

Jägermeister?
