### ISSUE TITLE
Accordion in FlatList: Header and Children disappear when typing content in <TextInput> in child

### ISSUE THREAD

**Issue by nickbuc1** [dooboolab/dooboo-ui-native#178]
**Describe the bug**
The Header and Children gradually disappear when collapsing / expanding the Accordion after typing text in <TextInput> of the child. The Accordion is in the RenderItem function of a flatlist.

Any suggestion on how to fix? I am thinking about setting up a fixed headerHeight.

**To Reproduce**
```javascript
    const activeRegattaGoalsList = [
        {
            id: 10,
            goalOrder: 1,
            goal: 'list goal',
            challenge: 'list 1. What needs to be improved',
            solution: 'How you plan to improve it',
            notes: 'SMART (Simple, Measurable, Achievable, Relevant, Time bound) goals to be accomplished to meet the next strategic goal.',
        },
        {
            id: 12,
            goalOrder: 2,
            goal: 'list goal',
            challenge: 'list 2. What needs to be improved',
            solution: 'How you plan to improve it',
            notes: 'Lorem Ipsum...',
        }, 
]


    renderGoal = ({ item }) => (
        <Accordion
            style={styles.dropDownHeader}
            contentVisible={false}
            invisibleElement={IC_ARR_DOWN}
            visibleElement={IC_ARR_UP}
            header={
                <View>
                    <Text style={styles.header2}>{item.goalOrder}. {item.goal}</Text>
                </View>
            }
        >
            <View style={styles.dropDownContent} >

                <View style={styles.insideLineStyle}></View>
                <Text style={styles.header3}>
                    Challenge
                </Text>
                <TextInput style={styles.textInputBox2} multiline={true}>
                    {item.challenge}
                </TextInput>
                <Text style={styles.header3}>
                    Solution
                </Text>
                <TextInput style={styles.textInputBox2} multiline={true}>
                    {item.solution}
                </TextInput>
                <Text style={styles.header3}>
                    Notes
                </Text>
                <TextInput style={styles.textInputBox2} multiline={true}>
                    {item.notes}
                </TextInput>
            </View>
        </Accordion>
    );

keyExtractor = (item) => String(item.id);

    return (
        <ScrollView style={styles.container}>

            <Text style={styles.header1}>Goals</Text>
            <FlatList
                keyExtractor={keyExtractor}
                data={activeRegattaGoalsList}
                renderItem={renderGoal}
            />
        </ScrollView>
    );
const styles = StyleSheet.create({
    container: {
        flex: 1,
        paddingTop: 0,
        backgroundColor: '#fff',
    },
    dropDownHeader: {
        paddingTop: 10,
    },
    dropDownContent: {
        alignItems: 'stretch',
        marginLeft: 0,
        marginRight: 30,
        width: Dimensions.get('window').width - 60,
    }, 
    textInputBox2: {
        height: 80,
        borderWidth: 1,
        borderColor: CColors.greyGroup.lightGrey,
        borderRadius: 12,
        padding: 10,
        margin: 5,
        marginLeft: 0,
        marginRight: 0,
        fontFamily: 'futura-book',
        fontSize: 15,
    },
    insideLineStyle: {
        borderBottomColor: CColors.greyGroup.lightGrey,
        borderBottomWidth: 1,
        paddingTop: 5,
        paddingBottom: 5,
        marginLeft: 20,
        marginRight: 20,
    },
    header1: {
        fontFamily: 'futura-medium-bt',
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'left',
        color: CColors.blueGroup.blue5,
        marginTop: 10,
        paddingLeft: 30,
    },
    header2: {
        fontFamily: 'futura-medium-bt',
        fontSize: 18,
        fontWeight: 'bold',
        textAlign: 'left',
        padding: 10,
        color: CColors.blueGroup.blue5,
        paddingLeft: 30,
    },
    header3: {
        fontFamily: 'futura-medium-bt',
        fontSize: 15,
        fontWeight: 'bold',
        textAlign: 'left',
        padding: 5,
        marginLeft: 10,
        color: CColors.blueGroup.blue5,
        paddingLeft: 0,
    },
});
```

1. Display the content
2. Expand one of the goals
3. Type text in one of the TextInput boxes
4. Collapse goal
5. Expand the same goal
6. Collapse the same goal
7. The goal will gradually disappear until it is no longer visible

**Expected behavior**
The header and child should not disappear when collapsing / expanding the accordion

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hyochan** [comment]
Could you kindly share your current behavior? Looks bit abstract to understand the current status.

**Comment by nickbuc1** [comment]
The first time Accordion is called, it displays the header properly, with the arrow icon. When typing on the header or arrow, it show the content of all the children, with the right contentHeight. However, when I enter any content into the fixed size TextInput boxes and tap again on the header, the accordion collapses, the children gets hidden but it hides a bit of the bottom of the header. If I type on the header again, instead of expanding to show the children, it hides a little more of the header / title. The whole display shifts up, i.e. what was below that specific accordion shifts up on the screen every time the header is tapped., until the header is completely hidden and the component has shifted up to occupy most (not all) the space of the original accordion.
I am using Accordion in multiple places and get the same behavior everywhere. It works very well until typing text in one of the TextInput boxes. The size of the content/children does not change because I use TextInput boxes with a pre-set size. Typing one letter is enough to get the behavior. Is the contentHeight and headerHeight dynamically recalculated at each iteration? 
Thanks a lot for your help.

**Comment by hyochan** [comment]
@nickbuc1 Any demo movie or the picture you can share?

**Comment by nickbuc1** [comment]
@hyochan attached a set of pictures. Expand Collapse work well in the first 2 pictures. In picture 3, type in some text in the box. Collapsing works byt when trying to expand again in picture 5, the second item starts to disappear. As shown in the following pictures, the more you type the more the item disappears.
[accordion.zip](https://github.com/dooboolab/dooboo-ui-native/files/4247700/accordion.zip)

I hope this helps give you a good idea of what is happening and thanks for any help!

PS: The yellow warning is due to using ScrollView together with FlatList, and unrelated.

**Comment by hyochan** [comment]
cc @JongtaekChoi

**Comment by JongtaekChoi** [comment]
@nickbuc1 
In your codes, the style of the Accordion has padding-top value 10. So calculated height is not enough to cover your children. I don't know why, but I found that the height of children decreases due to the influence of parent views when typing. As a result, each time the height of children is recalculated, the size of the parent view decreases and the height of the child view decreases and repeats.
If you remove the padding value than it may work correctly.

**Comment by nickbuc1** [comment]
@JongtaekChoi 
Changing the padding helps avoiding that the header disappears but did not help with avoiding that the content/child disappears. I think what happens is when typing text in a TextInput in a child, the size of the contentHeight gets recalculated but it seems that evt.nativeEvent.layout.height works only the first time and returns 0 afterwards. So the content has no height and never gets shown.

As the height of each child does not change, it is enough to avoid rewriting contentHeight in the onLayout function 
    const onLayout = (evt) => {
        if (!contentHeight) 
            setContentHeight(evt.nativeEvent.layout.height);
    };

If the size of the child can change, you would need to calculate the new contentHeight in a different way...
