### ISSUE TITLE
[Warning] useNativeDriver

### ISSUE THREAD

**Issue by 27leaves** [dooboolab/dooboo-ui-native#189]
**Describe the bug**
From react-native 0.62 on it is required to give the option `useNativeDriver`. If not, every time there comes a warning like this:
```
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`
    in SwitchToggle (at Switch.js:39)
```

**To Reproduce**

1. Go to a page with a switch toggle
2. You can see the warning

**Expected behavior**
No warning

**Additional context**
`@dooboo-ui/native-switch-toggle` version: `0.4.1`

**Comment by andreipfeiffer** [comment]
Prepared a PR for this:
https://github.com/dooboolab/dooboo-ui-native/pull/191

**Comment by hyochan** [comment]
Merged!

**Comment by 27leaves** [comment]
Thank you, guys!
