### ISSUE TITLE
Accoridon improvement

### ISSUE THREAD

**Issue by hyochan** [dooboolab/dooboo-ui-native#199]
**Describe the bug**

Currently, the `Accordion` component doesn't work nicely in `dooboo-ui` web. Also, since `useNativeDriver` is now necessary, we need to migrate the component to work in `mobile` too.

**To Reproduce**

Test the `Accordion` component in both `web` and `ios` or `android` storybook

**Expected behavior**

Work as expected.[Accordion collapsible](https://github.com/oblador/react-native-collapsible)

**Screenshots**
![image](https://user-images.githubusercontent.com/27461460/83474966-4833f300-a4c8-11ea-859f-1572538bcfe6.png)
![Y8Bgtu6GLk](https://user-images.githubusercontent.com/27461460/83475554-8aa9ff80-a4c9-11ea-9fef-6705cf86a7d6.gif)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser chrome
- Version Version 83.0.4103.61 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: iPhone11
- OS: iOS 13.3
- Version: 11.5

**Comment by DevYuns** [comment]
I am interested in working on this. can you assign this to me?

**Comment by hyochan** [comment]
Closes via #201 #205
