### ISSUE TITLE
[Feature] Checkbox

### ISSUE THREAD

**Issue by JeffGuKang** [dooboolab/dooboo-ui-native#202]
**Is your feature request related to a problem? Please describe.**

Feature request: Checkbox. 

![image](https://user-images.githubusercontent.com/216363/84352949-31447d80-abf9-11ea-85cc-5938a68c48b1.png)
[source](https://material-ui.com/components/checkboxes/)

**Describe the solution you'd like**

- It muse have no dependencies.
- It must works with same style for all platforms.
- It must have a modifiable style.
- It muse be acceptable custom image.

**Describe alternatives you've considered**

**Additional context**

Refs
- https://material-ui.com/components/checkboxes/
- https://react-native-elements.github.io/react-native-elements/docs/checkbox.html

**Comment by JinleeJeong** [comment]
**Goal**

- Implementing CheckBox component with test codes
- Adding storybooks for CheckBox component and sub-components.

**It must need all check.**

The indeterminate property can help you to achieve a 'check all' effect.

![image](https://user-images.githubusercontent.com/45163013/90787222-7561a600-e33f-11ea-912a-3a491b7cb16a.png)

**Library**

- [styled-components](https://www.styled-components.com/)
- [storybook.js](https://storybook.js.org/)
- [@testing-library/react-native](https://www.npmjs.com/package/@testing-library/react-native)

**Comment by JeffGuKang** [comment]
@JinleeJeong Thanks to take this feature. I assigned you.

**Comment by JeffGuKang** [comment]
@hyochan I found that you implemented the `CheckBox` component in #320. And some contributors are making `CheckBox` also as https://github.com/dooboo-ui-turtle/dooboo-ui/tree/turtle/Checkbox. 

It could be better to do not update by yourself more cause other contributors will do that ASAP. 😃

**Comment by hyochan** [comment]
@JeffGuKang Followed that. Sorry that I've missed this thread is being continued! Actually, @JinleeJeong, you can just refer to the implementation and you may completely re-design it if you want to build up your own thing.

The current implementation is still roughly developed so any breaking changes or destruction is fine either as long as there is communication 😃

**Comment by hyochan** [comment]
Looks like this lovely feature is missing in our [storybook](https://dooboolab.github.io/dooboo-ui/?path=/docs/components-accordion--example)
