### ISSUE TITLE
Switch Toggle Doesn't support RTL

### ISSUE THREAD

**Issue by anaskhraza** [dooboolab/dooboo-ui-native#210]
**Describe the bug**
On RTL switch toggle goes out of boundary as shown below. This bug is also reported in the following deprecated repo https://github.com/dooboolab/react-native-switch-toggle/issues/33

<img width="208" alt="64347044-e9eee800-cffb-11e9-9e19-cadd22c9ee35" src="https://user-images.githubusercontent.com/13957414/85386785-b2323c00-b54c-11ea-8f7d-27c3030c03f2.png">

**To Reproduce**
Use RTL layout with simple switch toggle navigation

```js
<SwitchToggle
  containerStyle={styles.switchContainer}
  circleStyle={styles.switchCircle}
  switchOn={toggleCompare}
  onPress={() => setToggleCompare(!toggleCompare)}
  circleColorOff={colors.superWhite}
  circleColorOn={colors.superWhite}
  backgroundColorOff={colors.darkGray}
  backgroundColorOn={colors.linkedinColor}
  duration={500}
/>
```

**Expected behavior**
On Toggle on RTL, position of circle should move in opposite direction

**Screenshots**
<img width="208" alt="64347044-e9eee800-cffb-11e9-9e19-cadd22c9ee35" src="https://user-images.githubusercontent.com/13957414/85386785-b2323c00-b54c-11ea-8f7d-27c3030c03f2.png">

**Comment by JeffGuKang** [comment]
Thank you for issue reporting. I will check ASAP.

**Comment by hyochan** [comment]
@JongtaekChoi Can you also look into this one?

**Comment by JongtaekChoi** [comment]
@anaskhraza 

Could you show me the details of the containerStyle and the circleStyle of your source code? 
You've probably set the position of inner circle. But, SwitchToggle was not made in consideration of such a situation.
The inner circle is located to the right of the initial position if the switchOn value is true and it is located to the initial position if the value is false.

I think it would be better to rename props items to support RTL.
| current name | changed name | other |
|------|---|---|
|switchOn|switchOff| It is needed to change value type ('left' or 'right') |
|backgroundColorOn/Off | backgroundColorRight/Left | |
|circleColorOn/Off | circleColorRight/Left | |

Another option is to add RTL to the prop so that the inner circle moves in reverse.

**Comment by hyochan** [comment]
> @anaskhraza
> 
> Could you show me the details of the containerStyle and the circleStyle of your source code?
> You've probably set the position of inner circle. But, SwitchToggle was not made in consideration of such a situation.
> The inner circle is located to the right of the initial position if the switchOn value is true and it is located to the initial position if the value is false.
> 
> I think it would be better to rename props items to support RTL.
> 
> current name	changed name	other
> switchOn	switchOff	It is needed to change value type ('left' or 'right')
> backgroundColorOn/Off	backgroundColorRight/Left	
> circleColorOn/Off	circleColorRight/Left	
> Another option is to add RTL to the prop so that the inner circle moves in reverse.

Could you give a `PR` for such proposal?

**Comment by anaskhraza** [comment]
@hyochan following is the containerStyle and circleStyle that I'm using

`switchCircle: {
        width: 10,
        height: 10,
        borderRadius: 10,
        backgroundColor: colors.white,
    },
    switchContainer: {
        width: 30,
        height: 15,
        borderRadius: 10,
        backgroundColor: colors.gray,
        padding: 2,
    },`

Since RTL mirror the application off position of the switch aligns to the right as shown in the snapshot below. so when the switch has been triggered to on then, toggle switch calculates the end Position of circle as it was doing for the normal left align layouts

`   var endPos = props.containerStyle && props.circleStyle
        ? props.containerStyle.width -
            (props.circleStyle.width +
                props.containerStyle.padding * 2)
        : 0;
    var circlePosXEnd = endPos;`

I think the easiest solution will be to use a prop for RTL and after calculating endPosition, multiply the position with -1 if it is on RTL mode.

<img width="334" alt="Screen Shot 2020-07-19 at 11 36 04 AM" src="https://user-images.githubusercontent.com/13957414/87870783-fe3d9880-c9b3-11ea-95a9-8ea4cc55238e.png">

<img width="350" alt="Screen Shot 2020-07-19 at 11 37 03 AM" src="https://user-images.githubusercontent.com/13957414/87870807-21684800-c9b4-11ea-9044-4df7bb41315d.png">
