### ISSUE TITLE
Compile error when using UI components after installing "dooboo-ui".

### ISSUE THREAD

**Issue by s-ong-c** [dooboolab/dooboo-ui-native#230]
**Describe the bug**

**To Reproduce**

`First (General)`
1. using "dooboo-cli" or "expo-cli" create Project or anything React-Native projects
2. install dooboo-ui
3. components UI 
  ```tsx
  import Button from 'dooboo-ui';

  function Sample():ReactElement {
       return <Button text="test"></Button> 
  }
 ```
   
<img width="400" alt="스크린샷 2020-07-07 오후 8 19 50" src="https://user-images.githubusercontent.com/34743425/86772898-d84cf580-c08f-11ea-95f0-439225ccb3cc.png">

`Second  ( Storybook, Gatsby)`
1. using create Project ( anything React-Native projects)
2. install dooboo-ui
3. components UI 
  ```tsx
import { Button } from 'dooboo-ui';
import { ContainerDeco } from '../../storybook/decorators';
import { action } from '@storybook/addon-actions';
import { storiesOf } from '@storybook/react-native';
import styled from 'styled-components/native';
import { text } from '@storybook/addon-knobs';
function Default(): React.ReactElement {
  const [facebookLoading, setFacebookLoading] = useState<boolean>(false);
  const [googleLoading, setGoogleLoading] = useState<boolean>(false);

  return (
    <Container>
      <Button
        isLoading={false}
        text="😀 😎 👍 💯"
        onPress={action('Clicked')}
      />
      <Button
        style={{
          marginVertical: 40,
        }}
        containerStyle={{
          marginTop: 32,
        }}
        isDisabled={true}
        text={text('button text', 'this is disabled')}
      />

    </Container>
  );
}
 ```
   
<img width="600" alt="스크린샷 2020-07-07 오후 8 43 04" src="https://user-images.githubusercontent.com/34743425/86775744-970a1500-c092-11ea-8dc6-df9c85267f5d.png">

or

<img width="400" alt="스크린샷 2020-07-07 오후 8 48 17" src="https://user-images.githubusercontent.com/34743425/86776538-3f1fde00-c093-11ea-98bd-5fac6dab51b0.png">

**Expected behavior**

- OS: [mac os]
- Browser [chrome]

**Additional context**
The first problem is solved by referring to the url.  (https://github.com/expo/expo-cli/tree/master/packages/webpack-config#include-modules)

BUT Second Problem is Not Solve!!

**Comment by hyochan** [comment]
Related #229

**Comment by s-ong-c** [comment]
@hyochan I also referred to #299 .So I solved the first problem(general Project) , but not the second(Environment like Storybook or gatsby Project).

**Comment by hyochan** [comment]
Let's dig in!

**Comment by hyochan** [comment]
@s-ong-c Do you think this should still be opened?

**Comment by s-ong-c** [comment]
@hyochan  I think it should still be open.
Because I haven't... solved it yet. Be digging

**Comment by hyochan** [comment]
@s-ong-c Could you give any news on this issue?

**Comment by s-ong-c** [comment]
@hyochan  Sorry for the late reply.
I think you can close this issue.

Also, if we get to this content, we will open an issue.
