### ISSUE TITLE
[Enhance] Refactor native StyleSheet to style-components.

### ISSUE THREAD

**Issue by Sandwichj** [dooboolab/dooboo-ui-native#26]
Enhancement derived from a discussion of https://github.com/dooboolab/hackatalk-mobile/issues/34, suggested by @hyochan 

We should use [style-components](https://github.com/styled-components/styled-components), instead of `StyleSheet` of `react-native`, due to the following issues.
- More difficult to manage `StyleSheet` styles than `styled-components`.
- Hard to migrate common components coded by `styled-components` from other projects to `@dooboo-ui/native`.
- `@dooboo-ui/native` has the both `StyledSheet` and `styled-components`. Should use one of them to keep code consistency.

**Comment by hyochan** [comment]
@Sandwichj Thanks for organizing it. FYI, I've already installed `styled-component` in [this library](https://github.com/dooboolab/dooboo-ui-native/blob/cb0fa2f5a0f262db6c383c1c7c27d4e0ca2a2f1d/package.json#L32).

**Comment by hyochan** [comment]
> * More difficult to manage `StyleSheet` styles than `styled-components`.

We are looking to support both for those who aren't using it.

> * Hard to migrate common components coded by `styled-components` from other projects to `@dooboo-ui/native`.
- [x] Already installed `styled-component`.

> * `@dooboo-ui/native` has the both `StyledSheet` and `styled-components`. Should use one of them to keep code consistency.
- I have [answered](https://github.com/dooboolab/dooboo-ui-native/pull/27#issuecomment-547773126) your similar question in your `PR` given.
