### ISSUE TITLE
Error when running "yarn add @dooboo-ui/core"

### ISSUE THREAD

**Issue by harwall** [dooboolab/dooboo-ui-native#263]
Hello. I hope this is the good place to report this.

**Describe the bug**
I was trying to install the component SwitchToggle (found here : https://github.com/dooboolab/dooboo-ui/tree/master/main/SwitchToggle)

I tried running "yarn add @dooboo-ui/core" as described on the link above. And the following error appeared : 
error An unexpected error occurred: "https://registry.yarnpkg.com/@dooboo-ui%2fcore: Not found".

**To Reproduce**

simply run "yarn add @dooboo-ui/core" in your terminal

**Comment by hyochan** [comment]
Sorry, this should be `yarn add dooboo-ui`!
