### ISSUE TITLE
Mistakes in the README : import instructions of Select

### ISSUE THREAD

**Issue by harwall** [dooboolab/dooboo-ui-native#265]
Hello,

Not sure if I should report this here (as it's not really a bug report) but I believe there is a mistake in the examples given for "Select" in the README.

**It first says to write :**
import { Item, Select } from 'dooboo-ui';

**Then :** 
import { Item, Select } from '../../main/Select';

**While I believe it should be :** 
import {Item, Select} from 'dooboo-ui/Select';

This is the one that worked for me while the two others didn't.

**Comment by hyochan** [comment]
@harwall Thanks for the report! 
@filoscoder Could you kindly look into this?

**Comment by harwall** [comment]
Oupsie, forgot the URL to make it easier for you guys. Here you go.

https://github.com/dooboolab/dooboo-ui/tree/master/main/Select


First line of "Import" and first line of "usage"

**Comment by hyochan** [comment]
Thanks for the report! I hope you try `dooboo-ui@0.0.12` and come back when you still face the problem.

**Comment by harwall** [comment]
@hyochan 
Thanks. "Select" works fine for me with 0.0.12 but I think you forgot to change this in the README ;)
![image](https://user-images.githubusercontent.com/26182082/88863613-8a955a00-d203-11ea-942f-448b912788c3.png)


Also, since I updated from 0.0.11 to 0.0.12 the import of "SwitchToggle" doesn't work anymore.
![image](https://user-images.githubusercontent.com/26182082/88863704-bdd7e900-d203-11ea-98fb-94c27ef4a3a3.png)

**Comment by filoscoder** [comment]
Thank you for tracking these details! I'll take a quick look

**Comment by harwall** [comment]
Still got the issue for 'SwitchToggle'.

I ran "yarn add dooboo-ui" once more and checked if the import example is the same as in my code.

**Comment by hyochan** [comment]
@harwall Sorry for that. Could you try `0.0.14` and come back?

**Comment by hyochan** [comment]
@harwall Actually, the `paths` were not organized well so I've done the refactor in #270.

I've just released `0.0.15`. Hope you can try that.

**Comment by harwall** [comment]
Works fine for me now. Thanks a lot :)
