### ISSUE TITLE
[Feature] How about adding duration prop to the LoadingIndicator component?

### ISSUE THREAD

**Issue by oh3vci** [dooboolab/dooboo-ui-native#272]
**Is your feature request related to a problem? Please describe.**

To make the LoadingIndicator component disappear, it have to rely on the elements outside of it.
And it doesn't have animating prop of ActivityIndicator for solving this problem.

**Describe the solution you'd like**

It is disappeared after the time entered.

**Describe alternatives you've considered**

Add duration prop of number type. Using this prop, it is changed animating prop to false after duration time.

**Additional context**

https://reactnative.dev/docs/activityindicator#animating

**Comment by hyochan** [comment]
Well the idea of this element was to provide more customized utilities over [ActivityIndicator](https://reactnative.dev/docs/activityindicator). 

Your idea can be done conditionally outside the element.
```
isLoading
  ? <LoadingIndicator .../>
  : <Button .../>
```

Furthermore, I think your idea can be applied to components such as [AlertDialog](https://fqk.io/bootstrap-alert-dialog/).

**Comment by oh3vci** [comment]
@hyochan Then, how about using duration prop for maximum time of showing the LoadingIndicator? It is also unnecessary?

**Comment by hyochan** [comment]
Hm.. well I think you can give a proposal and try out. Come to think of it again, I think this can be helpful.

**Comment by oh3vci** [comment]
@hyochan Ok. I will try it.
