### ISSUE TITLE
first PR test fail: `[error]Resource not accessible by integration`

### ISSUE THREAD

**Issue by JeffGuKang** [dooboolab/dooboo-ui-native#274]
**Describe the bug**
PR test is always failed by GitHub Actions in first contribution.

refs: https://github.com/actions/first-interaction/issues/10

Example PR: https://github.com/dooboolab/dooboo-ui/runs/934834176

```
 /usr/bin/docker run --name c20184e65c4be38043b8ae5adc4dba411299_b9dbed --label 87c201 --workdir /github/workspace --rm -e INPUT_REPO-TOKEN -e INPUT_ISSUE-MESSAGE -e INPUT_PR-MESSAGE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/dooboo-ui/dooboo-ui":"/github/workspace" 87c201:84e65c4be38043b8ae5adc4dba411299
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
Checking if its the users first contribution
Checking...
Checking...
Checking...
Checking...
Adding message: Hey there thank you for you first pull request~! to pull request 273
##[error]Resource not accessible by integration
```
**To Reproduce**

1. fork this repository 
2. make PR
3. github action test failed

**Expected behavior**

Have to pass test

**Screenshots**
![image](https://user-images.githubusercontent.com/216363/89101391-67082480-d43a-11ea-9242-2d5a2f324a32.png)

**Desktop (please complete the following information):**

Doesn't matter.

**Smartphone (please complete the following information):**
Doesn't matter.

**Additional context**

**Comment by JeffGuKang** [comment]
@hyochan How about to remove the action?

**Comment by hyochan** [comment]
Hm. This is not clear to me since we didn't setup any `first-interaction` setup in github action. Do you have any idea how we can resolve this?

**Comment by JeffGuKang** [comment]
> Hm. This is not clear to me since we didn't setup any `first-interaction` setup in github action. Do you have any idea how we can resolve this?

It looks a kind of bug as https://github.com/actions/first-interaction/issues/10. 
I will check and update the issue whether we got same testing result or not
whenever people create first PR.

**Comment by hyochan** [comment]
![image](https://user-images.githubusercontent.com/27461460/89103093-3c25cc80-d44a-11ea-91a2-69deeed449b7.png)

We only have greetings installed. I am not sure how to remove this.

**Comment by JeffGuKang** [comment]
`Greetings` is using `first-interaction` action as I linked above. I will make PR to remove this after some investigation tomorrow.

**Comment by hyochan** [comment]
Sounds great!

**Comment by hyochan** [comment]
@JeffGuKang Just removed it!

**Comment by JeffGuKang** [comment]
Solved: https://github.com/dooboolab/dooboo-ui/commit/535adaa61e085bccb225f07bf320c11f4e705ced
