### ISSUE TITLE
'react-native-svg' module is not contained in the library dependency

### ISSUE THREAD

**Issue by oh3vci** [dooboolab/dooboo-ui-native#302]
**Describe the bug**
'react-native-svg' module is not contained in the project dependency.

**To Reproduce**

1. install dooboo-ui
2. import SwitchToggle Component in my project
3. it shows unable to resolve module error.

**Screenshots**
![Simulator Screen Shot - iPhone 11 - 2020-08-13 at 14 31 27](https://user-images.githubusercontent.com/20278777/90097924-0948d600-dd72-11ea-8f3a-341c19435aa6.png)

**Smartphone (please complete the following information):**

- Device: [iPhone11]
- OS: [iOS13.6]

**Additional context**

To solve this problem, it seems to be removed react-native-svg dependency from Arrow of Select Component or add this module to library dependency.

**Comment by JongtaekChoi** [comment]
Thanks for your report. 
I would like to add 'react-native-svg' and 'styled-components' to the library dependencies.  
@hyochan How do you think about this?

**Comment by hyochan** [comment]
> Thanks for your report.
> I would like to add 'react-native-svg' and 'styled-components' to the library dependencies.
> @hyochan How do you think about this?

How about adding peerDependency? Our goal is however not to make too many deps too.

**Comment by JongtaekChoi** [comment]
I think #310 solved this problem. 
So I will close this issue. 
If you think that it's not solved, please reopen it. 
Thanks.
