### ISSUE TITLE
[Feature][DatePicker]

### ISSUE THREAD

**Issue by oh3vci** [dooboolab/dooboo-ui-native#305]
**Is your feature request related to a problem? Please describe.**
Feature request: DatePicker

- box for floating date picker

![image](https://user-images.githubusercontent.com/20278777/90400500-88723d00-e0d7-11ea-903d-c25c5e6ef38b.png)

- date picker

![image](https://user-images.githubusercontent.com/20278777/90399050-4ba54680-e0d5-11ea-9251-aaf15951b71d.png)

[source](https://material-ui.com/components/pickers/#datepickers)

**Describe the solution you'd like**
- picker title customizing
- styling (text color, size, margin etc...)
- enable to select start date and end date

**Describe alternatives you've considered**
- is it possible to use CalendarCarousel of packages for implementing DatePicker.

**Additional context**
Refs
- https://material-ui.com/components/pickers/#datepickers

**Comment by hyochan** [comment]
@oh3vci What a wonderful issue. I am not quite sure how the implementation could look like. In addition to that, I'd like to inform you that `CalendarCarousel` currently isn't working nicely in `android` especially with dragging. I am not quite sure but when it has swiped right, it intermittently cancel the event to move the calendar.

@shljessie We might have to add `scrollable` props to disable `swipe gestures` to support above date picker since it doesn't need that buggy behavior (gesture).

After that this might look possible to integrate to `datepicker` and we might have to think of reusing it. Maybe just by adding `peerDependency` to `@dooboo-ui/calendar-carousel` would be fine.

**Comment by shljessie** [comment]
@hyochan  Yes I'll look into that! 
@oh3vci I'm afraid that our CalendarCarousel currently doesn't have a date-picker feature.
Currently this is what our Calendar Carousel looks like in dooboo-ui. Sorry the readme.md hasn't been updated. If you want to add a date-picker function I'm afraid you'll have to create one in addition to the darkmode feature that the calendar image above seems to have. I'm more than happy to answer any questions you have about the code!  Feel free to ask!

<img width="423" alt="Screen Shot 2020-08-04 at 6 52 56 PM" src="https://user-images.githubusercontent.com/59305253/90494636-a8107080-e17e-11ea-9792-3d48776f5da0.png">

**Comment by bumjoo** [comment]
I wanna set the calendar to the top of the screen when selecting a date. 
Can I use **@react-native-community/react-native-modal** ?

If not, can you recommend any other way to set the calendar to the top?

**Comment by shljessie** [comment]
@bumjoo If you are using the Calendar for your personal project idont think using @react-native-community will be a problem ! But if you are trying to contribute that to doobooui I’ll ask @hyochan @JongtaekChoi   Just for clarification, how the Calendar Carousel is structured is stated here https://link.medium.com/xXdNQ7Li98. The SafeAreaView is the largest wrapper container you could put elements inside of it to use such as a date selector below the Calendar. Im still working on the Calendar and the changes havent all been pushed yet if there are any bugs let me know!

**Comment by hyochan** [comment]
> I wanna set the calendar to the top of the screen when selecting a date.
> Can I use **@react-native-community/react-native-modal** ?
> 
> If not, can you recommend any other way to set the calendar to the top?

I hope you to use [official modal](https://reactnative.dev/docs/modal) only. Our motivation for `dooboo-ui` is to create things pure as much as possible.

**Comment by JeffGuKang** [comment]
#332 is merged. But it doesn't support web environment yet.
