### ISSUE TITLE
[Select] not working on Android

### ISSUE THREAD

**Issue by harwall** [dooboolab/dooboo-ui-native#311]
**Describe the bug**
The select feature works perfectly on IOS but I simply can't get it to work on Android. 

I can open and close it but nothing happens when I click on an option. Once again, it's working perfectly on ios.

**To Reproduce**
I followed the instructions as written here : [https://github.com/dooboolab/dooboo-ui/tree/master/main/Select](url)

And this is my code.

```js
import {Select, SelectItem} from 'dooboo-ui';
import React from 'react';
import {useState} from 'react';

import styled from 'styled-components/native';

/** COMPONENTS */
const CustomSelectContainer = styled.View`
  width: 100%;
  height: 50px;
  justify-content: center;
  background-color: white;
  border-radius: 4px;
  elevation: 5;
  box-shadow: 0px 1px 1px #b3b3b3;
  shadow-opacity: 0.4;
  shadow-radius: 1px;
  margin-top: 50px;
`;

export function ExamplePage() {
  const [selectedValue, onSelectedValue] = useState<string>('En');
  const [isOpen, toggleSelect] = useState<boolean>(false);

  return (
    <CustomSelectContainer>
      <Select
        opened={isOpen}
        loading={false}
        disabled={false}
        showArrow={true}
        bordered={true}
        value={selectedValue}
        onSelect={(value): void => onSelectedValue(value)}
        onOpen={(isOpen): void => toggleSelect(isOpen)}>
        <SelectItem value="english">english</SelectItem>
        <SelectItem value="français">français</SelectItem>
        <SelectItem value="deutsch">deutsch</SelectItem>
      </Select>
    </CustomSelectContainer>
  );
}
```

**Expected behavior**
When on Android, on click on an option/SelectItem, the select should close itself and show the selected value.

**Smartphone (please complete the following information):**

- Device: Pixel 2, emulated on android studio
- OS: Android, don't know the version

It's been tested on other devices by some of my colleagues and they also got the issue on Android.

Is there anyone who got the same issue or who knows the answer ? I'm kinda getting desperate :/

**Comment by JongtaekChoi** [comment]
This issue related to [this issue](https://github.com/facebook/react-native/issues/27232). If select items are visible, those are out of the parent view(Container of the Select) and it's not touchable now at the android platform. And related pr is waiting for merge. Regardless of this, we are trying to fix it as well in another way.

**Comment by harwall** [comment]
Thanks for the answer. By any chance do you have the link to the pr waiting for merge ?

**Comment by JongtaekChoi** [comment]
The pr is [here](https://github.com/facebook/react-native/pull/29039).

**Comment by harwall** [comment]
Thanks a lot !
