### ISSUE TITLE
[Feature] Card

### ISSUE THREAD

**Issue by greatSumini** [dooboolab/dooboo-ui-native#313]
**Is your feature request related to a problem? Please describe.**
nope

**Describe the solution you'd like**
a Card component : Simple rectangular container.
- title, subtitle, coverImage support
- loading, disabled, raised status support
- styling

![Screen Shot 2020-08-22 at 11 38 23 AM](https://user-images.githubusercontent.com/48555121/90946852-ff0e9200-e46b-11ea-9a76-dee48f2aec46.png)

[go figma workspace to get more details](https://www.figma.com/file/f7LwH54h08Q6nsBNs7bCvd/DOOBOO-UI-CARD?node-id=0%3A1)

implementing it [here](https://github.com/doobooUI-card-team/dooboo-ui)

**Comment by JeffGuKang** [comment]
@greatSumini Thanks to suppose the new Feature.
