### ISSUE TITLE
[Question] How can I swipe down to close the PinchZoomSliderModal?

### ISSUE THREAD

**Issue by bumjoo** [dooboolab/dooboo-ui-native#345]
Hello.

PinchZoomSliderModal seems to be a useful component for displaying multiple images.

By the way, is there a way to close the PinchZoomSliderModal by swiping down or up? 

Like most apps that display multiple images such as KakaoTalk, Facebook and Instagram, 
I'd like to have the ability to close it with a swipe down in pinch zoom.

**Comment by hyochan** [comment]
Oh.. good question! This isn't currently implemented :(
