### ISSUE TITLE
[Accordion] How i am changing the arrows images position?

### ISSUE THREAD

**Issue by AbdulRehman197** [dooboolab/dooboo-ui-native#35]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hyochan** [comment]
Which one are you refering? There are few ui components in our list.

**Comment by AbdulRehman197** [comment]
I am talking  about arrow up and down  images  you have specified any type invisibleImage prop and visibleImage prop but there is not styling prop for these images

**Comment by hyochan** [comment]
@AbdulRehman197 So you are talking about `Accordion`. I think it'd be better to refactor `images` into `element`. How do you think? I'll try to do this and come back to you.

**Comment by hyochan** [comment]
I've just released `@dooboo-ui/native-accordion@4.0.0`. Would you like to try this and come back? I've exposed react `Element` instead of `ImageProps`.

**Comment by IamN5** [comment]
I think its related to this, when using a React Element instead of ImageProps the Accordion wont collapse or expand, no matter what "contentVisible" or "contentVisibleOnLoad" values are.
