### ISSUE TITLE
[Button] Documentation Is Outdated

### ISSUE THREAD

**Issue by 0916dhkim** [dooboolab/dooboo-ui-native#350]
**Describe the bug**
Props table and examples are not in sync with the actual source code of `Button` component.

https://github.com/dooboolab/dooboo-ui/blob/93d7e602c6bc0a42fa0696b7240392900612cf45/main/Button/README.md#L9-L27

https://github.com/dooboolab/dooboo-ui/blob/93d7e602c6bc0a42fa0696b7240392900612cf45/main/Button/README.md#L147-L171

https://github.com/dooboolab/dooboo-ui/blob/93d7e602c6bc0a42fa0696b7240392900612cf45/main/Button/index.tsx#L51-L68

- `outlined` : Declared in `Props` but unused & undocumented.
- `color` : Declared in `Props` but unused & undocumented.
- `Accent` : Documented, but not declared in `Props`.
- `Secondary` : Used in an example, but undocumented & undeclared.

**Comment by JeffGuKang** [comment]
It's your hawk's eye! I'll be wating for your PR.

**Comment by 0916dhkim** [comment]
@JeffGuKang Leave it to me, chief! I'll open a PR when I'm ready. Just wanted to make sure that I'm not missing anything here.
