### ISSUE TITLE
[Select] is using react-native-svg module

### ISSUE THREAD

**Issue by JeffGuKang** [dooboolab/dooboo-ui-native#353]
**Describe the bug**

Unable to resolve module `react-native-svg` for `dooboo-ui` v0.0.18.
`Select` component is using react-native-svg. 

**To Reproduce**

1. Install dooboo-ui v0.18 without `react-native-svg`
2. Run
3. Error 

**Expected behavior**

Remove `react-native-svg` from `Select` Component or move the component to `packages` folder managed by lerna.

**Screenshots**

![image](https://user-images.githubusercontent.com/216363/93973925-fe8d5200-fdaf-11ea-9c07-15ef1de8f6c2.png)

**Desktop (please complete the following information):**

X

**Smartphone (please complete the following information):**

X

**Additional context**

X

**Comment by JongtaekChoi** [comment]
This issue is similar with #302.
I think we need to replace the `svg` to another image format like `png`.

**Comment by hyochan** [comment]
It is not a good idea to put all the images inside the `lib`. How about adding them to `required` props and use them in `storybook` only.
