### ISSUE TITLE
[Feature] Slider component

### ISSUE THREAD

**Issue by Sandwichj** [dooboolab/dooboo-ui-native#41]
derived from https://github.com/dooboolab/dooboo-ui-native/issues/37

[Discussion for component interface and spec](https://github.com/dooboolab/dooboo-ui-native/issues/47)

## Goal

- Implementing Slider component with test codes
- Adding storybooks for Slider component and sub-components.
- Examples

## Hackatalk UI Design

- [https://www.figma.com/file/0WDPu0Cn9upY1TQcLuhLev/prototype?node-id=38%3A48](https://www.figma.com/file/0WDPu0Cn9upY1TQcLuhLev/prototype?node-id=38%3A48)
    - Slider

<img src="https://user-images.githubusercontent.com/11019960/69893885-198f6100-135b-11ea-9f31-ff077d2cfefd.png" width="200" />

- Material UI slider to refer
    - [https://material-ui.com/components/slider](https://material-ui.com/components/slider/)

## Libraries

- [styled-components](https://www.styled-components.com)
- [storybook.js](https://storybook.js.org/)
- [@testing-library/react-native](https://www.npmjs.com/package/@testing-library/react-native)

## Structure

- Rail
    <img src="https://user-images.githubusercontent.com/11019960/69906030-67aa7000-1400-11ea-8fc2-ac7ec8be76c3.png" width="200" />

- Track
    <img src="https://user-images.githubusercontent.com/11019960/69906047-a6402a80-1400-11ea-8f44-b762cc6f809b.png" width="200" />

- Thumb
    <img src="https://user-images.githubusercontent.com/11019960/69906058-c7a11680-1400-11ea-8073-79ed641e739d.png" width="200" />

- Label
    <img src="https://user-images.githubusercontent.com/11019960/69906068-e1daf480-1400-11ea-8f83-bfada347fa15.png" width="200" />

### [Rail] requires:
- Draw a line.

### [Marks] requires:
- mark
    <img src="https://user-images.githubusercontent.com/11019960/69906084-1b136480-1401-11ea-92b0-0451b53a0547.png" width="200" />
- Customizable step (default: 1)
    <img src="https://user-images.githubusercontent.com/11019960/69906090-32eae880-1401-11ea-9aa4-59056c458102.png" width="200" />
- `mark` reveals if `step` is not 1.

### [Track] requires:
- Draw a line until the value of Slider.
- Three kinds of icon and effects

### [Thumb] requires:
- Active animation effect
- Three kinds of icon and effects

### [Label] requires:
- Position icon with text

### [Slider] requires:
- [Track] on [Rail] and [Marks]
- Customizable [Thumb]
- Customizable [Label]
- [Thumb] moves as `step` size.
- Show [Label] on press
- Modifiable with two [Thumb]s.
- It can be disabled.

**Comment by Sandwichj** [comment]
assignees

@daheeahn
@yongpilmoon
@cupid0824

**Comment by daheeahn** [comment]
Please Assign me!

**Comment by tony3918** [comment]
please assign me :)

**Comment by Sandwichj** [comment]
[Update] Arranged slider structure with sub-components.

**Comment by dipsiiiiiiiiii** [comment]
Please assign me!😁

**Comment by Yuni-Q** [comment]
Please Assign me!

**Comment by hankkuu** [comment]
plz assign me

**Comment by Sandwichj** [comment]
Updated [Slider task status](https://github.com/dooboolab/dooboo-ui-native/issues/47).
Please check the status before you start your new task.
When you choose a task, please let contributors know what task you would take, to prevent duplicated works.

**Comment by Sandwichj** [comment]
Updated [Slider task status](https://github.com/dooboolab/dooboo-ui-native/issues/47).

**Comment by Sandwichj** [comment]
Updated [Rail] props. #47

**Comment by Sandwichj** [comment]
Updated [Slider task status](https://github.com/dooboolab/dooboo-ui-native/issues/47).
