### ISSUE TITLE
[Feature] Snackbars Component

### ISSUE THREAD

**Issue by JongtaekChoi** [dooboolab/dooboo-ui-native#46]
derived from #37

### Goal
Implementing `Snackbars` component with test codes
Adding storybooks for Slider component and sub-components.

### Examples
Hackatalk UI Design
https://www.figma.com/file/0WDPu0Cn9upY1TQcLuhLev/prototype?node-id=39%3A543
 Snackbars

### Material UI snackbars to refer
https://material-ui.com/components/snackbars
https://material.io/components/snackbars/

### Libraries
styled-components
storybook.js
@testing-library/react-native

**Comment by godon019** [comment]
## Reference
- https://material.io/components/snackbars/
- [code to refer](https://github.com/xotahal/react-native-material-ui/blob/master/src/Snackbar/Snackbar.react.js)
- [behavior guide](https://material.io/components/snackbars/#behavior)

**Comment by godon019** [comment]
## Basic Todo
- [x] setup branch, maintain - by @JongtaekChoi
- [x] component setup - by @Ta2rim
- [x] story setup - by @Ta2rim
- [x] test setup - by @Ta2rim
- [x] short/long closing time - @godon019 is working on it!
  - [x] test - by @JongtaekChoi 
- [x] add action test - by @Ryz0nd 
- [x] consecutive snackbars - by @JongtaekChoi 

Further Todo(feature) lists will be listed below as comments
any idea about new `todo`? put comment here starting with`[Feature]`, `[Discuss]` or `[Modify]` !

If you want to work on any feature here, just comment like this [example](https://github.com/dooboolab/dooboo-ui-native/issues/46#issuecomment-565687402)!
and please implement it with below !
- simple test code
- simple usage on storybook

**Comment by godon019** [comment]
Assign me!

**Comment by taejs** [comment]
assign me

**Comment by woojong92** [comment]
assign me

**Comment by godon019** [comment]
`[Feature]` alert when the text content is longer than 2 lines

> Snackbars contain a text label that directly relates to the process being performed. On mobile, the text label can contain up to two lines of text.

**Comment by godon019** [comment]
`[Feature]` styling with shadow
> Snackbar containers use a solid background color with a shadow to stand out against content.

**Comment by godon019** [comment]
`[Feature]` Action(purple color text in the screenshot) 

- default click behavior might close snackbars
- will be at right side of snackbar when short
  ![image](https://user-images.githubusercontent.com/10363850/70807318-ac6ed780-1e00-11ea-96b6-28e3095cad25.png)

- then it will be at the bottom of it when long
  ![image](https://user-images.githubusercontent.com/10363850/70807386-ce685a00-1e00-11ea-87f4-fef83c79a45d.png)

**Comment by godon019** [comment]
`[Modify]` edit closing time to 4 and 10 secs
> Snackbars appear without warning, and don't require user interaction. They automatically disappear from the screen after a minimum of four seconds, and a maximum of ten seconds.
- current closing times are 1500ms(short) and 3000ms(long)

**Comment by godon019** [comment]
`[Feature]` Consecutive snackbars
- Multiple snackbars should be appear one by one(not showing more than one at a time)
- might need to use FIFO stack for implementing it
![consecutive](https://user-images.githubusercontent.com/10363850/70844268-0ebbec80-1e82-11ea-95b3-3bc1977236b5.gif)

**Comment by hyochan** [comment]
@godon019 Please write in English~!

**Comment by godon019** [comment]
`[Feature]` `[Discuss]` Snackbars should appear above FABs
[example](https://material-ui.com/components/snackbars/#snackbars-and-floating-action-buttons-fabs)
- how to implement it when we have no implemented FABs yet? any ideas are welcome

**Comment by godon019** [comment]
~~`[Feature]` appear/disappear animation~~

![appear-animation](https://user-images.githubusercontent.com/10363850/70844302-6c503900-1e82-11ea-8764-baa019dce385.gif)

> closed it as it can be implemented by [Action](https://github.com/dooboolab/dooboo-ui-native/issues/46#issuecomment-565461856) behavior

**Comment by godon019** [comment]
~~I will take [appear/dissapear animation](https://github.com/dooboolab/dooboo-ui-native/issues/46#issuecomment-565686928)!~~

**Comment by woojong92** [comment]
I will take [styling with shadow](https://github.com/dooboolab/dooboo-ui-native/issues/46#issuecomment-565460684)! :)

**Comment by Ryz0nd** [comment]
assign me

**Comment by MoonKim-isMe** [comment]
I will take [alert when the text content is longer than 2 lines](https://github.com/dooboolab/dooboo-ui-native/issues/46#issuecomment-565459686)

**Comment by JongtaekChoi** [comment]
> `[Feature]` `[Discuss]` Snackbars should appear above FABs
> [example](https://material-ui.com/components/snackbars/#snackbars-and-floating-action-buttons-fabs)
> 
> * how to implement it when we have no implemented FABs yet? any ideas are welcome

I think that It can be implemented by the user and we don't need to concerning it.

**Comment by Ryz0nd** [comment]
I'll take [Action(purple color text in the screenshot)](https://github.com/dooboolab/dooboo-ui-native/issues/46#issuecomment-565461856)

**Comment by JongtaekChoi** [comment]
I'll take  [Consecutive snackbars](https://github.com/dooboolab/dooboo-ui-native/issues/46#issuecomment-565464083)
