### ISSUE TITLE
[Discussion] Slider component interface

### ISSUE THREAD

**Issue by Sandwichj** [dooboolab/dooboo-ui-native#47]
derived from #41 

This issue is to discuss [Slider] interface(like props) or others what [Slider] should have.

**CONTRIBUTORS**
- @YongPilMoon 
- @tony3918 
- @hankkuu 
- @daheeahn 
- @Sandwichj 

<img src="https://user-images.githubusercontent.com/11019960/73301465-2d215000-4256-11ea-974f-e45be574a4a4.png" width="400" />
<img src="https://user-images.githubusercontent.com/11019960/73301499-3c080280-4256-11ea-9095-80c40703191f.png" width="400" />

## Task status
|Component  |Implement                  |Test                             |Storybook      |Component files |
|-------------|---------------------|---------------------|--------------|-----------------|
|Slider            |Done                      |Done except gesture test                    |Done         |Done                    |
|Rail               |Done                             |Done                          |-                |Done                   |
|Marks           |Done                            |Done                           |-             |Done                   |
|Track            |Done                            |Done                     |-              |Done               |
|Thumb          |Done                           |Done                     |-               |Done              |
|Label             |Done                           |Done                        |-             |Done         |

### Slider
|Prop              |Type                   |Default                  |Purpose              |Required |
|-------------|----------------|------------------|-----------------|---------|
|hideMark         |boolean                         |false              |hide marks                                 |X             |
|hideLabel         |boolean                         |true              |hide label                                 |X             |
|autoLabel         |boolean                         |false             |show label automatically                                 |X             |
|step               |number              |1                             |distance between two marks                             |X             |
|defaultValue |number              |0                             |default value       |X             |
|minValue       |number              |0                             |minimum value    |X             |
|maxValue      |number              |100                            |maximum value   |X             |
|mark                |ReactElement                |-             |custom mark                            |X             |
|customMarkWidth |number                |-                |custom mark width                 |required if custom mark             |
|startMark        |boolean                          |true        |show the first mark if ture     | X             |
|endMark         |boolean                          |true        |show the last mark if true      |X             |
|markStyle       |StyleProp<ViewStyle>  |-   |mark style      |X             |
|railStyle|StyleProp<ViewStyle>  |-   |rail style      |X             |
|trackStyle|StyleProp<ViewStyle>  |-   |track style      |X             |
|thumbStyle|StyleProp<ViewStyle>  |-   |thumbstyle      |X             |
|labelStyle |StyleProp<ViewStyle>  |-   |label style      |X             |
|labelTextStyle |StyleProp<ViewStyle>  |-   |label text style      |X             |
|labelSize |number  |-   |label size      |X             |
|onChange      |(value: number) => void |-                             |`change` event handler      |X             |

### Rail
|Prop              |Type                             |Default                  |Purpose              |Required |
|--------------|----------------------|----------|-------------------|---------|
|testID              |string                            |-               |testing                                      |X             |
|style                |StyleProp\<ViewStyle\>|-            |rail style                                       |X             |

### Marks
|Prop              |Type                             |Default                  |Purpose              |Required |
|--------------|----------------------|----------|-------------------|---------|
|testID              |string                            |-               |testing                                      |X             |
|sliderWidth      |number|-                  |sllider width                                          |O             |
|style                |StyleProp\<ViewStyle\>|-            |marks style                                       |X             |
|mark                |ReactElement                |-             |custom mark                            |X             |
|customMarkWidth |number                |-                |custom mark width                 |required if custom mark             |
|step                 |number                          | 1             |distance between two marks |X             |
|startMark        |boolean                          |true        |show the first mark if ture     | X             |
|endMark         |boolean                          |true        |show the last mark if true      |X             |
|disabled          |boolean                         |false        |disable mark press                    |X             |
|onInit               |(markValues: number[], markPositions: number[]) => void \| Promise\<void\>|- | `event` fired on mount      |X             |
|onMarkPress  |(value: number, position: number, index: number) => void \| Promise\<void\>|- | `event` fired on mark press  |X             |

### Track
|Prop              |Type                             |Default                  |Purpose              |Required |
|-------------|----------------------|------------------|-----------------|---------|
|testID              |string                            |-               |testing                                      |X             |
|style                |StyleProp\<ViewStyle\>|-            |track style                                       |X             |
|percent         |number           |-                               |position of Thumb                          |O             |

### Thumb
|Prop              |Type                             |Default                  |Purpose              |Required |
|-------------|----------------------|------------------|-----------------|---------|
|testID              |string                            |-               |testing                                      |X             |
|percent     |number                         |12                               | position of thumb                    |X              |
|size               |number                         |12                               | size of thumb                    |X              |
|scaleValue               |number               |Animated.Value(0.01)                               | animation scale                    |X              |
|opacityValue |number                         |Animated.Value(0.12)                               | animation opacity                    |X              |
|customThumb |React.ReactElement |-               | Custom thumb                    |X              |

### Label
|Prop              |Type                             |Default                   |Purpose              |Required |
|-------------|----------------------|------------------|-----------------|---------|
|testID              |string                            |-               |testing                                      |X             |
|percentValue   |Animated.Value              |-     |position of Label with animation |O               |
|value   |number              |-     |value to display |O               |
|size               |number                         |32                               | size of thumb                    |X              |

#### Issues
- Resizing in storybook
- ~Horizontal mode~
- disabling
- gesture out of line or thumb

#### More
- Multiple thumbs
- Custom thumb as designed in [Figma](https://www.figma.com/file/0WDPu0Cn9upY1TQcLuhLev/prototype?node-id=38%3A48)

**Comment by tony3918** [comment]
If possible, I would like to participate in testing the components

**Comment by Sandwichj** [comment]
> If possible, I would like to participate in testing the components

@tony3918 
Surprised by your enthusiasm!
You can take anything you want if the things are not in progress.
What component would you like to take? They are possible to work independently.

**Comment by tony3918** [comment]
Thank you @Sandwichj 
Since Slider, Rail, and Track components are currently in progress, I'll go for testing Rail and Track

**Comment by Sandwichj** [comment]
@tony3918 
Great!
How about taking [Track] tests first?
They are possible to be implemented separately, though some test may not be possible to code.
And it gives a chance that someone could take [Rail] tests during you implement [Track] tests.
We can improve code and design step by step. (Code can't be implemented perfectly at once in programming as you know.)

Small code and many PRs are better in open source and collaboration.

**Comment by tony3918** [comment]
@Sandwichj Sounds perfect. Thanks for your guidance
