### ISSUE TITLE
[Feature Request] Rating

### ISSUE THREAD

**Issue by JeffGuKang** [dooboolab/dooboo-ui-native#53]
**Is your feature request related to a problem? Please describe.**

New Rating component related to #37.

**Describe the solution you'd like**

Ref: https://material-ui.com/components/rating
Do not use external library such as `react-native-vector-icon`.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by devethan** [comment]
I wanna take this.

**Comment by Saehanseul** [comment]
I wanna assign

**Comment by devethan** [comment]
@JeffGuKang @Saehanseul @yunjeongloper
I did refactoring [Rating] component and add README file. check it please.

**Comment by JeffGuKang** [comment]
To do until Jan.5.2020

- [ ] Launch and test the component (New assign members)
- [ ] Apply addon-knobs to Storybook (‘@storybook/addon-knobs’)
- [x] Update README.md
- [x] Next feature suggestion here

**Comment by downy158** [comment]
I wanna assign.

**Comment by downy158** [comment]
Done
[x] Update README.md
[x] Launch and test the component (New assign members)

To do until Jan.15.2020
[] Apply addon-knobs to Storybook (‘@storybook/addon-knobs’)
[] Add ration animation

**Comment by downy158** [comment]
Done
- [x] Update README.md
- [x] Launch and test the component (New assign members)

To do until Jan.15.2020 with @devohno 
- [ ] Apply addon-knobs to Storybook (‘@storybook/addon-knobs’)
- [ ] Update test code

**Comment by hyochan** [comment]
> Done
> 
> * [x]  Update README.md
> * [x]  Launch and test the component (New assign members)
> 
> To do until Jan.15.2020 with @devohno
> 
> * [ ]  Apply addon-knobs to Storybook (‘@storybook/addon-knobs’)
> * [ ]  Update test code

@devethan How is the `todo` until `Jan 15` going?
