### ISSUE TITLE
[Feature Request] TinderCard

### ISSUE THREAD

**Issue by hyochan** [dooboolab/dooboo-ui-native#82]
Implement [TinderCard] like [react-native-deck-swiper](https://github.com/alexbrillant/react-native-deck-swiper)

Sample Images below.

![image](https://user-images.githubusercontent.com/27461460/70804371-a75a5a00-1df9-11ea-9b52-1f778bfc9b5a.png)

![image](https://user-images.githubusercontent.com/27461460/70804382-af19fe80-1df9-11ea-9bdb-f89d4e50574a.png)

**Comment by devethan** [comment]
me :)

**Comment by devethan** [comment]
@hyochan Can I create this component on 'src/components/shared/TinderCard'?

**Comment by hyochan** [comment]
Yes you should!
